# Generated by Django 3.1.2 on 2020-11-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student_Details'},
        ),
    ]
