# Generated by Django 3.1.2 on 2020-11-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20201102_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('Address', models.TextField(max_length=200)),
                ('Age', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Student_Details',
            },
        ),
    ]
