# Generated by Django 3.1.2 on 2020-11-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_emp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp',
            options={'verbose_name_plural': 'Employee_Details'},
        ),
        migrations.AddField(
            model_name='emp',
            name='gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female')], default='NA'),
        ),
    ]
