# Generated by Django 3.1.2 on 2020-11-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20201104_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='newstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Age', models.IntegerField(max_length=200)),
                ('Address', models.TextField(max_length=200)),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('favorite_fruit', models.TextField(choices=[('Orange', 'Orange'), ('Apple', 'Apple'), ('Grape', 'Grape'), ('Kiwi', 'Kiwi')])),
                ('Email', models.EmailField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'New_Studentdetails',
            },
        ),
    ]
