# Generated by Django 3.1.2 on 2020-11-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_newstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='Confirmpassword',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='emp',
            name='password',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
