# Generated by Django 3.1.2 on 2020-11-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20201111_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstudent',
            old_name='Email',
            new_name='email',
        ),
    ]
