# Generated by Django 3.1.2 on 2020-11-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20201111_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='fileupload',
            field=models.FileField(default='NA', upload_to='Documents'),
        ),
    ]
